#!/bin/bash
#Event-driven programming

#set sound Y/N
echo ________________________________________
echo __________ "marlov0005 (((*)))"
echo __________ Programmer: Alejandro Duhalde
echo __________ MARLO AUTOMATA
echo __________ LOG PATH:/tmp/marlo/log_marlo.log
echo __________ Voice Assistant controller chatgp, gemini, GOOGLE 

espeak -k cantonese "...HI, Alex..." 
espeak -k cantonese "...Starting..."
echo ________________________________________
echo ________________________________________   
echo ______Modern apis requiere____" * * * "
echo __________Estructured_________" * * * " 
echo ______Mongodb_________________" * * * "
echo _______________________________________
echo ____VERIFICATION SETTING PARAMETERS_____
echo ________________________________________ 


 echo "| set | DATA IN PARAMETERS SETS " 
 echo "|check| database connection"
 espeak -k cantonese " checking database connection" 

 echo "| set | LOG START SERVICES "
 echo "| set | BACKUPS LOG "
 echo " ! Making BACKUP "
 echo " ! writing LOG REPORT"
 echo "| set | SYSTEMD CI(CD) SERVICES "
 echo "| set | LOG CRON SERVICES "
 
  echo ___Charging control panel PYTHON___
  espeak -k cantonese " Charging control panel PYTHON"
    #coordenas looker
    #espeak -k cantonese " Charging control panel JAVA"





   echo ___GOOD BYE_________ _ _ _ _ _ _
#echo 'export PATH="$PATH:/home/alex/GIT/Data_integration_clean_code/bash/1_SCRIPTING"' >> ~/.bash_profile
#echo 'export PATH="$PATH:/home/alex/GIT/Data_integration_clean_code/bash/1_SCRIPTING"' >> ~/.bashrc
